spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  config:
    import: optional:file:.env[.properties]

  security:
      oauth2:
        client:
          registration:
            naver:
              clientId: ${NAVER_ID}
              clientSecret: ${NAVER_KEY}
              scope:
                - email
                - profile
              client-name: Naver
              authorization-grant-type: authorization_code
              redirect-uri: https://winnerone.site:8080/login/oauth2/code/naver
            kakao:
               clientId: ${KAKAO_ID}
               clientSecret: ${KAKAO_KEY}
               scope:
                - profile_nickname
                - profile_image
                - account_email
               authorizationGrantType: authorization_code
               redirectUri: https://winnerone.site:8080/login/oauth2/code/kakao

          provider:
            naver:
                authorization-uri: https://nid.naver.com/oauth2.0/authorize
                token-uri: https://nid.naver.com/oauth2.0/token
                user-info-uri: https://openapi.naver.com/v1/nid/me
                user-name-attribute: response

            kakao:
                authorization-uri: https://kauth.kakao.com/oauth/authorize
                token-uri: https://kauth.kakao.com/oauth/token
                user-info-uri: https://kapi.kakao.com/v2/user/me
                user-name-attribute: response

  h2:
    console:
      enabled: true

  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  data:
    web:
      pageable:
        default-page-size: 10
        page-parameter: page
        size-parameter: pageSize
        one-indexed-parameters: true

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

cookie:
  domain: localhost

