spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  config:
    import: optional:file:.env[.properties]

  h2:
    console:
      enabled: true

  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  data:
    web:
      pageable:
        default-page-size: 10
        page-parameter: page
        size-parameter: pageSize
        one-indexed-parameters: true

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
